INFO    : main sequencer started @ [2021/05/05 14:46:38]
INFO    : sequencer to be run in [PRODUCT] mode, by [kunlun]
DEBUG   : welcome to main sequencer
INFO    : ACQUIRING QUEUE[__ask_question_FIFO][False][180]
INFO    : ACQUIRED QUEUE[__ask_question_FIFO] within 0s
INFO    : RELEASED QUEUE[__ask_question_FIFO]
DEBUG   : dfbv
ERROR   : Did not received '>' within [10] seconds, buf tails []
ERROR   :   File "D:\kunlun\script\product\main.py", line 18, in main_sequencer
ERROR   :     uut.send("dir\r", expect=">", timeout=10)
ERROR   :   File "D:\kunlun\libs\protocols\conn.py", line 134, in send
ERROR   :     raise Exception(msg)
ERROR   : Exception: Did not received '>' within [10] seconds, buf tails []
INFO    : main sequencer failed @ [2021/05/05 14:46:52]
